# • To configure Anonymous FTP upload, you'll need to make sure that the
# following is accomplished
# • vsftpd.conf is modified to allow anonymous FTP access and uploads
# • The directory /var/ftp/pub is configured with the appropriate permissions
# • The directory /var/ftp/pub is configured with the appropriate SELinux context
# label
# • The SELinux boolean ftpd_anon_write is set to on
# • Create a playbook that ensures that the vsftpd service is installed, enabled,
# the firewall is opened, and the above requirements are met. Define
# variables in the playbook to set vsftpd.conf parameters, and use these in a
# template
# • At the end of the playbook, verify connectivity, uploading the /etc/hosts
# file from localhost

- name: Install and configure vsftpd
  hosts: ansible1
  tasks:
    - name: Install vsftpd package
      package:
        name:
          - vsftpd
          - firewalld
        state: present
    - name: Make ftp root directory
      file:
        state: directory
        path: /var/ftp/pub
        # recurse: yes
        mode: '0777'
        # owner: foo
        # group: foo
    - name: Prepare vsftpd.conf file
      template:
        src: vsftpd.conf.j2
        dest: /etc/vsftpd/vsftpd.conf
        # owner: bin
        # group: wheel
        # mode: '0644'
    - name: Set ftpd_anon_write flag on and keep it persistent
      seboolean:
        name: ftpd_anon_write
        state: yes
        persistent: yes
    - name: Allow public upload in /var/ftp/pub
      sefcontext:
        target: '/var/ftp/pub(/.*)?'
        setype: public_content_rw_t
        state: present
    - name: Apply new SELinux file context to filesystem
      command: restorecon -irv /var/ftp/pub
    - name: Start services
      service:
        name: vsftpd
        state: started
        enabled: yes
    - name: Open firewall for ftp
      firewalld:
        zone: public
        service: ftp
        permanent: yes
        immediate: yes
        state: enabled



