---
- name: install custom facts
  hosts: all
  vars:
    remote_dir: /etc/ansible/facts.d
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ inventory_hostname_short }}.fact"
        dest: "{{ remote_dir }}"